# GoReleaser configuration for sieswi
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: sieswi
    main: ./cmd/sieswi
    binary: sieswi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: sieswi
    name_template: "sieswi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - INSTALL.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo

# Homebrew tap - uncomment when homebrew-tap repository is created
# brews:
#   - name: sieswi
#     repository:
#       owner: melihbirim
#       name: homebrew-tap
#     homepage: https://github.com/melihbirim/sieswi
#     description: "Blazing-fast SQL queries on CSV files with parallel processing"
#     license: MIT
#     install: |
#       bin.install "sieswi"
#     test: |
#       system "#{bin}/sieswi", "--version"
